name: 'Summarise dbt-contracts results'
branding:
  icon: 'table'
  color: 'magenta'
author: 'George Martin Marino'
description: 'Creates a summary table on actions to summarise results from dbt-contracts'
inputs:
  title:
    description: 'Title of the summary'
    required: false
    default: 'DBT Contracts results'
  path:
    description: 'Path to a JSON file which contains the output of a dbt-contracts execution as a list of annotations.'
    required: true
  repo-token:
    description: 'Token used to interact with the GitHub API.'
    required: true
  ignore-missing-file:
    description: 'Ignore if the file which contains annotations is missing'
    required: false
    default: 'true'
runs:
  using: 'ubuntu'
  main: 'scripts/summarise_results.sh'